/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ExampleFirst {}
  interface ExampleFive {}
  interface ExampleFour {}
  interface ExampleSecond {}
}

declare global {


  interface HTMLExampleFirstElement extends Components.ExampleFirst, HTMLStencilElement {}
  var HTMLExampleFirstElement: {
    prototype: HTMLExampleFirstElement;
    new (): HTMLExampleFirstElement;
  };

  interface HTMLExampleFiveElement extends Components.ExampleFive, HTMLStencilElement {}
  var HTMLExampleFiveElement: {
    prototype: HTMLExampleFiveElement;
    new (): HTMLExampleFiveElement;
  };

  interface HTMLExampleFourElement extends Components.ExampleFour, HTMLStencilElement {}
  var HTMLExampleFourElement: {
    prototype: HTMLExampleFourElement;
    new (): HTMLExampleFourElement;
  };

  interface HTMLExampleSecondElement extends Components.ExampleSecond, HTMLStencilElement {}
  var HTMLExampleSecondElement: {
    prototype: HTMLExampleSecondElement;
    new (): HTMLExampleSecondElement;
  };
  interface HTMLElementTagNameMap {
    'example-first': HTMLExampleFirstElement;
    'example-five': HTMLExampleFiveElement;
    'example-four': HTMLExampleFourElement;
    'example-second': HTMLExampleSecondElement;
  }
}

declare namespace LocalJSX {
  interface ExampleFirst {}
  interface ExampleFive {}
  interface ExampleFour {}
  interface ExampleSecond {}

  interface IntrinsicElements {
    'example-first': ExampleFirst;
    'example-five': ExampleFive;
    'example-four': ExampleFour;
    'example-second': ExampleSecond;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'example-first': LocalJSX.ExampleFirst & JSXBase.HTMLAttributes<HTMLExampleFirstElement>;
      'example-five': LocalJSX.ExampleFive & JSXBase.HTMLAttributes<HTMLExampleFiveElement>;
      'example-four': LocalJSX.ExampleFour & JSXBase.HTMLAttributes<HTMLExampleFourElement>;
      'example-second': LocalJSX.ExampleSecond & JSXBase.HTMLAttributes<HTMLExampleSecondElement>;
    }
  }
}


